<template>
  <div id="app">
    <NavBar />
    <router-view/>
  </div>
</template>


<script lang="ts">
 
import { Vue, Component} from 'vue-property-decorator';
import NavBar from '@/components/NavBar.vue';

@Component({
  components:{
    NavBar,
  }
})
export default class App extends Vue {}

</script>

<style lang="scss">
@import '@/assets/variables.scss';


* {
  box-sizing: border-box;
  padding: 0;
  margin: 0;
  scroll-behavior: smooth;

  font-family: 'Manrope';
}

body {
  /* ff 3.6+ */
  background:-moz-radial-gradient(circle at 3% 25%, rgba(0, 40, 83, 1) 0%, rgba(4, 12, 24, 1) 100%);

  /* safari 5.1+,chrome 10+ */
  background:-webkit-radial-gradient(circle at 3% 25%, rgba(0, 40, 83, 1) 0%, rgba(4, 12, 24, 1) 100%);

  /* opera 11.10+ */
  background:-o-radial-gradient(circle at 3% 25%, rgba(0, 40, 83, 1) 0%, rgba(4, 12, 24, 1) 100%);

  /* ie 10+ */
  background:-ms-radial-gradient(circle at 3% 25%, rgba(0, 40, 83, 1) 0%, rgba(4, 12, 24, 1) 100%);

  /* global 92%+ browsers support */
  background:radial-gradient(circle at 3% 25%, rgba(0, 40, 83, 1) 0%, rgba(4, 12, 24, 1) 100%);

  background-repeat: no-repeat;
  background-size: cover;
  min-height: 100vh;
}

a {
  color: unset;
  text-decoration: none;
}

.section-padding {
  padding: 4rem 6rem;
}

.section-margin {
  padding: 4rem 6rem;
}

.primary-color{
  color: $text-color;
}

.bg-primary{
  background-color: $bg-color-primary;
}

.bg-footer{
  background-color: $bg-footer;
}

.bg-blog{
  background-color: $bg-blog;
}

.bg-subtext{
  background-color: $subtext-color;
}

.subtext-color{
  color: $subtext-color;
}

.subtext-color-2{
  color: $subtext-color-2;
}

.bg-button{
  background-color: $bg-button;
}

.button-border-radius{
  border-radius: $button-border-radius;
}

.clickable{
  cursor: pointer;
}

.text-gradient{
    background: $text-gradient;
    background-clip: text;
    --webkit-background-clip: text;
    color: transparent;
    --webkit-text-fill-color: transparent;
}


.bar-gradient{
  background: $bar-gradient;
}

.indicator{
    position: relative;
}

.indicator::before{
    content: '';
    width: 38px;
    height: 3px;
    position: absolute;
    background: linear-gradient(103.22deg, #AE67FA -13.86%, #F49867 99.55%);
    top: -10px;
    left: 0px;
}

.main-heading{
  font-size: 3rem;
  font-weight: 900;
}

@media screen and (max-width:650px) {
  .main-heading{
    font-size: 40px;
  }
}

@media screen and (max-width:480px) {
  .main-heading{
    font-size: 36px;
  }
}

.section-heading {
  font-size: 34px;
  font-weight: 800;
  line-height: 45px;
}

@media screen and (max-width:640px) {
  .section-heading{
    font-size: 30px;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2021-12-12 23:29:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

.scale-up-center {
	-webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

@media screen and (max-width: 700px){
  .section-padding{
    padding: 4rem;
  }

  .section-margin{
    margin: 4rem;
  }
}


@media screen and (max-width: 500px){
  .section-padding{
    padding: 4rem 2rem;
  }

  .section-margin{
    margin: 4rem 2rem;
  }
}

</style>
